# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-26 03:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
