# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-28 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0007_delete_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=12)),
                ('nick_name', models.CharField(max_length=50, null=True)),
                ('passwd', models.CharField(max_length=20, null=True)),
                ('sex', models.IntegerField(null=True)),
                ('birthday', models.CharField(max_length=20, null=True)),
                ('ctime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
